version: "3"
services:
  springboot-api:
    # container_name: spring-api
    image: edvaldodev/milenio-capital
    restart: always
    build: .
    ports:
      - 8080-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
